services:
  reporter:
    image: io.gaitian/reporter
    environment:
      collabora.url: http://collabora:9980
    ports:
      - 8050:8000
    restart: unless-stopped

  collabora:
    image: collabora/code
    cap_add:
      - MKNOD
    environment:
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    ports:
      - 9980:9980
    healthcheck:
      test: [ "CMD-SHELL", "curl -k http://localhost:9980 && echo 'OK'" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 15s
    restart: unless-stopped