
collabora:
  url: http://localhost:9980

jodconverter:
  remote:
    enabled: true
    url: ${collabora.url}

server:
  port: 8000

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 4096MB

logging:
  level:
    io.gaitian: TRACE